---
stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
        service: ${REPO}
    triggers:
      - type: commit
    jobs:
      - name: Install dependencies
        type: builder
        curatedDockerImage: default
        artifact_dir: ''
        build_type: customimage
        script: npm install
        docker_image: node:10
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    jobs:
      - name: Deploy
        type: deployer
        target:
          region_id: ${REGION_ID}
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          application: ${CF_APP}
          api_key: ${API_KEY}
        script: |-
          #!/bin/bash
          cf push "${CF_APP}"
          # cf logs "${CF_APP}" --recent
